### ISSUE TITLE
Atualizar os dados do WICM

### ISSUE THREAD

**Issue by natalhenrique** [husanisantos/cotesi#10]
Projeto SiDAI (Sistema de Detecção e Alarme de Incêndios) - uma solução baseada em tecnologias da Internet das Coisas para comunicação de dados sem fio e baixo consumo de energia. Maria Luiza Tomaz Leal e Osvandre Alves Martins (GPCAA) - Apoio: Previne Incêndios Ltda.
--
Desenvolvimento de um dispositivo de vibração que auxilie a navegação de pessoas com deficiência visual. Gabriel Gonçalves Garcia e Natal Henrique Cordeiro

Projeto QUALIVNH-DVQPV - Soluções tecnológicas de apoio à verificação da qualidade de Válvulas Neurológicas para Hidrocefalia - Evolução de protótipos do DVQPV (Dispositivo de Verificação da Qualidade - Caracterísiticas de Pressão-Vazão.Miguel Marques Floriano e Osvandre Alves Martins (GPCAA) - Apoio: Ventura Biomédica Ltda.

Aplicação de Técnicas de Visão Computacional para inspeção de defeitos na superfície de chapas laminadas de aço no processo produtivo industrial. João Batista Lino e Natal Henrique Cordeiro.

GPCAA (Grupo de Pesquisa em Computação Aplicada à Automação) - Projetos de Pesquisa, Desenvolvimento e Inovação envolvendo automação e robótica com possibilidade de atuação de alunos como bolsista ou para TCC.Prof. Dr. Osvandre Alves Martins (GPCAA)

**Comment by lanjoni** [comment]
Dados atualizados com sucesso!
Confira em: https://github.com/husanisantos/cotesi/commit/1c21d1bcab23f9f7e69332b01246d20111fc2248
