### ISSUE TITLE
O Impacto da Computação Quântica no Futuro da Computação Distribuída 

### ISSUE THREAD

**Issue by unixr** [husanisantos/cotesi#11]
Palestra, quinta-feira 29/09/2022 das 10h00 às 12h00.
inscrições: https://suap.ifsp.edu.br/eventos/evento/1686/

A palestra visa apresentar uma pequena fração do futuro cenário para a Computação Quântica Distribuída, evidenciando os desafios a serem superados. Trata-se de um compilado dos resultados de vários artigos de pesquisadores, que através de suas pesquisas realizaram, ao longo das últimas duas décadas, apontamentos para soluções e desafios a serem superados para o alcance da Computação Quântica Distribuída. Em vários aspectos já existe um consenso entre os pesquisadores sobre uma estrutura ideal para um sistema distribuído de computação quântica. A corrida para o alcance da supremacia quântica envolve pesquisadores independentes, governos e grandes empresas públicas e/ou privadas. Algumas dessas grandes empresas consideradas Big Techs, líderes nessa corrida pela supremacia quântica, disponibilizam recursos quânticos de forma gratuita ou paga, a depender da aplicação, para que desenvolvedores, pesquisadores e estudantes experimentem algoritmos quânticos, a fim de que possam se preparar e contribuírem para o futuro da computação quântica em um contexto geral. Tópicos a serem abordados: * desenvolvimento de processadores quânticos; * protocolos Bizantinos à nível quântico; * internet quântica; * soluções híbridas clássica/quântica de hardware e software.

**Comment by husanisantos** [comment]
Será atualizado hoje no próximo commit
