### ISSUE TITLE
Link para o cadastro das palestras

### ISSUE THREAD

**Issue by eajardini** [husanisantos/cotesi#6]

**Comment by eajardini** [comment]
- Conceitos básicos de uma aplicação android - Quarta - 28/09 - 19:00: https://suap.ifsp.edu.br/eventos/inscricao_publica/1568/

- Gêmeos Digitais: Aplicações Práticas - Quinta - 29/09 - 8:00: https://suap.ifsp.edu.br/eventos/inscricao_publica/1607/

**Comment by eajardini** [comment]
- Do Zero a Startup - 28/09 - Quarta-feira - 08:00: https://suap.ifsp.edu.br/eventos/inscricao_publica/1608/

- Acessibilidade Web - 28/09 - Quarta-feira - 10:00: https://suap.ifsp.edu.br/eventos/inscricao_publica/1610/

- Conceitos básicos de uma aplicação android - Quarta - 28/09 - 19:00: https://suap.ifsp.edu.br/eventos/inscricao_publica/1568/

- Inteligência Artificial - Quarta-feira - 28/09 - 21:00:
https://suap.ifsp.edu.br/eventos/inscricao_publica/1611/

- Gêmeos Digitais: Aplicações Práticas - Quinta - 29/09 - 08:00: https://suap.ifsp.edu.br/eventos/inscricao_publica/1607/

**Comment by unixr** [comment]
Empreendedorismo – Educação Empreendedora - Segunda-feira - 10:00: https://suap.ifsp.edu.br/eventos/inscricao_publica/1612/  e  https://forms.office.com/r/EVfq4we3HM
