### ISSUE TITLE
Links das palestras

### ISSUE THREAD

**Issue by eajardini** [husanisantos/cotesi#8]
- COTESI - Como ser um líder e como os líderes inpiram todos por suas ações. Sexta 30/09/2022 08:00. https://suap.ifsp.edu.br/eventos/inscricao_publica/1637/

- COTESI - Carreira e Tecnologia para Estudantes e Profissionais. Sexta 30/09/2022 10:00. https://suap.ifsp.edu.br/eventos/inscricao_publica/1639/

**Comment by eajardini** [comment]
Mais duas palestras

- COTESI-Importância da Internet na sociedade atual. terça 27/09/2022 08:00. https://suap.ifsp.edu.br/eventos/inscricao_publica/1640/

- COTESI-Como conseguir o seu primeiro emprego em Infosec. terça 27/09/2022 10:00. https://suap.ifsp.edu.br/eventos/inscricao_publica/1641/    Esta palestra substitui a de Cibersegurança

**Comment by lanjoni** [comment]
Links atualizados! 
Confira em: https://github.com/husanisantos/cotesi/commit/067d1a37cd1412bcd0345f5a74d1c6fc55bb884c
