### ISSUE TITLE
Adicionar descrição das oficinas

### ISSUE THREAD

**Issue by lanjoni** [husanisantos/cotesi#9]
Adicionar abaixo do horário de oficinas de amanhã o campo explicando o funcionamento:

Cada aluno poderá se inscrever em até duas oficinas (uma que contemple o horário das 13:30 às 15:00 e outra das 15:30 às 17:00). Verificar temas conforme descritos:

13:30 às 15:00 - Oficinas:
Princípios básicos de backup e armazenamento de arquivos em nuvem (Professor Eder Pansani)
Introdução ao Sistema Operacional Linux ( Professora Cris)
Prazer, Docker (João Augusto Lissoni Lanjoni)
Hardware (Professor Ubiratan)

15:30 às 17:00:
Princípios básicos de utilização e configuração de bancos de dados para aulas do IFSP (Professor Eder Pansani)
Introdução ao Sistema Operacional Linux ( Professora Cris)
Prazer, Docker (João Augusto Lissoni Lanjoni)
Hardware (Professor Ubiratan)

**Comment by eajardini** [comment]
Minicursos - Terça-feira

Atenção, cadastrei os minicursos a seguir ANTES de falar por telefone com o João Augusto. Assim, o curso terá apenas uma única turma de 1,5 hora mas que deverá se inscrever nos dois minicursos. O João está sabendo dos detalhes.

COTESI-Princípios básicos de backup e armazenamento de arquivos em nuvem: 27/09/2022 13:30  - 15:00 - 30 vagas : https://suap.ifsp.edu.br/eventos/inscricao_publica/1708/

COTESI-Princípios básicos de backup e armazenamento de arquivos em nuvem: 27/09/2022 15:30 - 17:00 - 30 vagas : https://suap.ifsp.edu.br/eventos/inscricao_publica/1710/


COTESI-Prazer, Docker: 	27/09/2022 13:30 - 15:00 - 30 vagas : https://suap.ifsp.edu.br/eventos/inscricao_publica/1713/

COTESI-Prazer, Docker: 	27/09/2022 15:30  - 17:00 - 30 vagas : https://suap.ifsp.edu.br/eventos/inscricao_publica/1714/

COTESI-Princípios básicos de utilização e configuração de bancos de dados para aulas do IFSP: 27/09/2022 13:30 - 15:00 - 30 vagas : https://suap.ifsp.edu.br/eventos/inscricao_publica/1719/

COTESI-Princípios básicos de utilização e configuração de bancos de dados para aulas do IFSP: 27/09/2022 15:30 - 17:00 - 30 vagas : https://suap.ifsp.edu.br/eventos/inscricao_publica/1720/


Atenção, cadastrei os minicursos a seguir APÓS falar por telefone com o João Augusto. Assim, o curso terá apenas uma única turma de 3 horas.

COTESI-Introdução ao Sistema Operacional Linux: 27/09/2022 13:30 - 17:00 - 30 vagas: https://suap.ifsp.edu.br/eventos/inscricao_publica/1721/

COTESI-O Hardware: 27/09/2022 13:30 - 17:00 - 30 vagas: https://suap.ifsp.edu.br/eventos/inscricao_publica/1723/


Minicurso - Quarta-feira
Atenção, cadastrei os minicursos a seguir antes de falar por telefone com o João Augusto. Assim, o curso terá apenas uma única turma de 1,5 hora mas que deverá se inscrever nos dois minicursos. O João está sabendo dos detalhes.
COTESI - Prática de Fusão de Fibra: 	28/09/2022 13:30 - 15:00 - 30 vagas : https://suap.ifsp.edu.br/eventos/inscricao_publica/1716/

COTESI - Prática de Fusão de Fibra: 	28/09/2022 15:30 - 17:00 - 30 vagas :	https://suap.ifsp.edu.br/eventos/inscricao_publica/1717/
